name: Auto Create Release Branch

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Allows manual triggering

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get latest tag on master and check for existing release branch
        id: setup
        run: |
          git fetch --tags
          latest_tag=''
          release_branch=release/${{ env.date }}
          echo $release_branch
          if git show-ref refs/remotes/origin/$release_branch; then
            echo "exists"
            echo "release-branch=exists" >> $GITHUB_ENV
          else
            echo "not exist"
            echo "release-branch=none" >> $GITHUB_ENV
          fi
          echo "latest-tag=$latest_tag" >> $GITHUB_ENV
          echo "release-branch-name=$release_branch" >> $GITHUB_ENV

      - name: Create release branch if none exists and push
        if: env.release-branch == 'none'
        run: |
          git checkout -b ${{ env.release-branch-name }} origin/dev
          git push origin ${{ env.release-branch-name }}
          git log origin/master..${{ env.release-branch-name }} --oneline >> changes.txt
          gh pr create -d -B master -H ${{ env.release-branch-name }} --fill-verbose --title 'Release [${{env.date}}]' -l 'Release' -r 'pawan-kumar-deel'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the release branch if branch already exists
        if: env.release-branch == 'exists'
        run: |
          git config pull.rebase false
          git fetch origin ${{ env.release-branch-name }}
          git checkout ${{ env.release-branch-name }}
          git pull
          git merge dev
          git push origin ${{ env.release-branch-name }}
          git log origin/master..origin/${{ env.release-branch-name }} --oneline >> changes.txt
          gh pr edit {{ env.release-branch-name }} --title 'Release [${{env.date}}]' --fill-verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output
        run: |
          if [ "${{ env.release-branch }}" = "exists" ]; then
            echo "A release branch already exists."
          fi